name: 'Setup Ruby, JRuby and TruffleRuby'
description: 'Download a prebuilt Ruby and add it to the PATH in 5 seconds'
author: 'Benoit Daloze'
branding:
  color: red
  icon: download
inputs:
  ruby-version:
    description: 'Engine and version to use, see the syntax in the README. Reads from .ruby-version if unset.'
    required: false
    default: '.ruby-version'
outputs:
  ruby-prefix:
    description: 'The prefix of the installed ruby'
runs:
  using: 'node12'
  main: 'dist/index.js'
